apiVersion: v1
kind: Secret
metadata:
  name: {{ template "fullname" . }}-secret
  labels:
    app: {{ template "name" . }}
    chart: {{ .Chart.Name }}-{{ .Chart.Version | replace "+" "_" }}
    heritage: {{ .Release.Service }}
    release: {{ .Release.Name }}
type: Opaque
data:
  userlist.txt: |-
{{ include "userlist.txt.1.0.0" . | b64enc | indent 4 }}
  pgbouncer.ini: |-
{{ include "pgbouncer.ini.1.0.0" . | b64enc | indent 4 }}
