{{- if .Values.service.enabled  }}
apiVersion: v1
kind: Service
metadata:
  name: {{ default (include "pgbouncer.fullname" .) .Values.service.name }}
  labels:
    {{- include "pgbouncer.labels" . | nindent 4 }}
  annotations:
    {{- range $key, $value := .Values.service.annotations }}
      {{ $key }}: {{ $value | quote }}
    {{- end }}
spec:
  type: {{ .Values.service.type }}
  selector:
    {{- include "pgbouncer.selectorLabels" . | nindent 6 }}
  ports:
    - port: {{ .Values.servicePort }}
      targetPort: {{ .Values.internalPort }}
      protocol: TCP
      name: postgres
    - port: 6432
      targetPort: 6432
      protocol: TCP
      name: postgres
{{- end }}
